### ISSUE TITLE
Modify Literate Examples Generation

### ISSUE THREAD

**Issue by beorostica** [JuliaHealth/KomaMRI.jl#251]
The documentation should identify all .jl files that start with 'lit-' in the example folder and all its subfolders to determine which files will be processed by Literate.

**Comment by cncastillo** [comment]
![image](https://github.com/cncastillo/KomaMRI.jl/assets/5957134/1e72a22c-e14d-4962-8e22-43d87dfbc554)

This example is already depricated.
