### ISSUE TITLE
Add simulate function for debugging purposes

### ISSUE THREAD

**Issue by beorostica** [JuliaHealth/KomaMRI.jl#288]
The idea is to incorporate the simulation function `seqsim` already implemented in the `block-time-interpretation` branch, located in the file [SimulatorCore.jl](https://github.com/cncastillo/KomaMRI.jl/blob/block-time-interpretation/KomaMRICore/src/simulation/SimulatorCore.jl). It requires minimal adjustments before merging it into the `master` branch. In `run_sim_time_iter!` we just have to define it based on `run_sim_time_iter` and bypass everything inside.

**Comment by cncastillo** [comment]
I dont think this is longer needed.
