### ISSUE TITLE
Create Pluto example for fat_sat_low_field

### ISSUE THREAD

**Issue by beorostica** [JuliaHealth/KomaMRI.jl#291]

**Comment by cncastillo** [comment]
The path **MUST** be https://juliahealth.org/KomaMRI.jl/stable/generated/examples/Low-Field-CMRA-SNR-Fat-Optimization/

**Comment by cncastillo** [comment]
I don't like how the Pluto is displayed currently.

We could use PlutoStaticHTML.jl to export Pluto notebooks in documentation.

**Comment by cncastillo** [comment]
Already here since #304
