### ISSUE TITLE
Interpretation of '.seq' files is not matching with sequence designed on PyPulseq

### ISSUE THREAD

**Issue by ZemaTimoteo** [JuliaHealth/KomaMRI.jl#320]
### What happened?

First, thank you for your nice repository, I found it very useful.

However, I am struggling with an issue regarding the interpretation of '.seq' files. Apparently, KomaMRI interpretates each block of gradient built in PyPulseq, with the need to start and finish at 0.  

Here are the full concatenated blocks I want to perform in the simulations. However, as you can see they have unexpected behavior of going to zero between each block of gradients design in the Pypulseq.

![Slide1](https://github.com/JuliaHealth/KomaMRI.jl/assets/37109227/7d8345cd-c2f1-4f8b-b156-6a0e4e1fbb0d)

Here are an example of block 1 and 2 for Gz:
_Block 1 - Koma_
![Block1_Koma](https://github.com/JuliaHealth/KomaMRI.jl/assets/37109227/954191d8-38b1-477c-9767-e1bf1c212c79)
_Block 1 - Pulseq_
![Block1_Pulseq](https://github.com/JuliaHealth/KomaMRI.jl/assets/37109227/7b9ca15a-350f-4ebe-b70f-d16fd2831d31)
_Block 2 - Koma_
![Block2_Koma](https://github.com/JuliaHealth/KomaMRI.jl/assets/37109227/9fe20022-4a81-420a-ab94-54d8838ebad8)

_Block 1:2 - Koma_
![Block1to2_Koma](https://github.com/JuliaHealth/KomaMRI.jl/assets/37109227/feaeca8b-0880-4cbe-9942-4cb34b1ce149)
_Block 1:2 - Pulseq_
![Block1to2_Pulseq](https://github.com/JuliaHealth/KomaMRI.jl/assets/37109227/67318d0c-682e-4b27-a2f9-4386b05db9d4)

I feel like this shouldn't be the case, as I need to simulate the '.seq' and don't want to edit it in the Koma environment as it would make it a different sequence from the one I will design for further scanning.

Should I do something different, or is this something that needs to be update?

Best
ZemaTimoteo

### Environment

```Markdown
OS x86_64-w64-mingw32
Julia 1.9.4
KomaMRIPlots 0.7.8
KomaMRI 0.7.5
KomaMRICore 0.7.6
```

**Comment by cncastillo** [comment]
Hi!

Thanks for using Koma :smile:!

This issue is related to #205. While it looks weird, it is more of a plotting bug, as it has no impact on the simulations. The worst thing that it could do is to add a sample with amplitud 0 and duration 0 to the simulation, which has no effect.

Having said that, I don't think it is a hard one to solve. Could you provide this pulseq file to do some tests? 

In the meantime, we have tools to check what is actually being simulated. Take a look at the results of  `plot_seqd(seq)` (see it in the [docs](https://juliahealth.org/KomaMRI.jl/stable/api/#KomaMRIPlots.plot_seqd)). It would be good to update anyway as we recently fixed a bug #315 that could have an impact in the simulation.

Cheers!

**Comment by cncastillo** [comment]
I believe we found a case where this could affect the simulation, opened #321 to fix it.

**Comment by ZemaTimoteo** [comment]
> Having said that, I don't think it is a hard one to solve. Could you provide this pulseq file to do some tests?

- I attatch the seq file that is give me this trouble. It is a simple MSE sequence. 

[MSE_test_KomaMRI.zip](https://github.com/JuliaHealth/KomaMRI.jl/files/14576283/MSE_test_KomaMRI.zip)


- I tried to run the code `plot_seqd(seq)` but i got the following error message: 

`ERROR: MethodError: no method matching discretize(::Sequence; sim_params::Dict{String, Any})

Closest candidates are:
  discretize(::Sequence; simParams) got unsupported keyword argument "sim_params"
   @ KomaMRICore C:\Users\filia\.julia\packages\KomaMRICore\wY77R\src\datatypes\simulation\DiscreteSequence.jl:53`

**Comment by beorostica** [comment]
Hi @ZemaTimoteo!
Thank you for your MSE sequence we are going to perform some tests with it 😃.

Can you please update your KomaMRI version? That is why you see  `ERROR: MethodError: no method matching discretize ...`

**Comment by cncastillo** [comment]
Hi, to give an update on this. What we were doing differently. We hadn't added the heuristic that Pulseq uses for the first and last samples (more info here https://github.com/JuliaHealth/KomaMRI.jl/pull/321#issuecomment-2020348649j). It is an easy fix and should be solved this week.

**Comment by cncastillo** [comment]
This has been solved in the current dev version of Koma (master). In some cases, the samples `first` sample is not exactly the same, but the difference was very small and only happened when the sample duration `dt=0`, so it had no effect in the simulation.

`plot_seq`
![seq](https://github.com/JuliaHealth/KomaMRI.jl/assets/5957134/df33b965-0405-4b68-9b7c-e7b7e7842095)

`plot_seqd`
![seqd](https://github.com/JuliaHealth/KomaMRI.jl/assets/5957134/8ff32342-26c9-4ed7-adef-02a05f75a7d4)

Please let us know if you encounter any other issues!
