### ISSUE TITLE
[BUG] CodeCov Not Working

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaHealth/KomaMRI.jl#335]
### What happened?

Hey @DilumAluthge , 

Thanks for helping @cncastillo and co here for KomaMRI get set-up over here on JuliaHealth! Carlos and I were speaking however and it seems that their CodeCov no longer works properly. Both the `codecov.yml` file and `ci.yml` look perfectly fine to me. I also checked the CodeCov permissions here and all access permissions are granted to the GitHub app. 

It is quite curious as all my normal debugging has failed for this and I am a bit stumped. Is there some setting in JuliaHealth that I am not aware of that might be breaking CodeCov here?

Thanks! 

~ tcp :deciduous_tree: 

### Environment

```Markdown
On the latest response from a webhook to CodeCov, we see this:


{"detail":"You do not have permission to perform this action."}
```

**Comment by TheCedarPrince** [comment]
Hey @DilumAluthge, I'll let @cncastillo and @beorostica comment more here but with KomaMRI's set-up, currently, it uses a webhook to send out a codecov request. Carlos was saying this was previously working fine when they were not within JuliaHealth so it seems like something may have gone wrong in the transition over to here. 

It seems like whenever a PR is made or updated, a request gets sent via the webhook but this permission error keeps popping up.

**Comment by cncastillo** [comment]
Thanks @DilumAluthge! 

Just to complement this answer, the codecov is being sent correctly to https://app.codecov.io/gh/JuliaHealth/KomaMRI.jl, but the bot that creates the reports (like the one below) stopped working.

![image](https://github.com/JuliaHealth/KomaMRI.jl/assets/5957134/0b8aee5e-a5bf-4b7a-a611-ef22bc57dd24)

The PRs look good to me, so accepted them. @beorostica could you look at them?

**Comment by DilumAluthge** [comment]
Let's try this: I'm going to:
1. Remove the GitHub app from this repo
2. Delete the webhook
3. Reinstall the GitHub app on this repo

Let's see if that does anything.

**Comment by DilumAluthge** [comment]
Okay, I got the Codecov comment to be posted in https://github.com/JuliaHealth/KomaMRI.jl/pull/343

**Comment by DilumAluthge** [comment]
Okay and the Codecov commit statuses have now been created on https://github.com/JuliaHealth/KomaMRI.jl/pull/343

**Comment by TheCedarPrince** [comment]
So out of curiosity, what went wrong here @DilumAluthge ? Could you track down where things broke exactly? Or did you just reset all of CodeCov for the repository?

**Comment by cncastillo** [comment]
Thanks @DilumAluthge and @TheCedarPrince for all your time :pray:. I wouldn´t have been able to fix it alone.

What a weird bug. I read in other places that the turn-it-on-and-off approach also worked for them. We will just double-check that everything works today (@beorostica), and I will close this issue :smile:.
