### ISSUE TITLE
GSOC Proposal Issue Tracking: Part 2

### ISSUE THREAD

**Issue by rkierulf** [JuliaHealth/KomaMRI.jl#350]
### Feature Request

Part 2) Tracking for objectives in GSOC proposal (July 15 - August 26):

Note: the tasks below besides the first and last bullet point fall into the "stretch" goal part of the project and may not be able to be completed, depending on how long other parts take

- [x] #349
- [x] #354 
- [x] #355
- [x] #356
- [x] Write blog post for JuliaHealth website documenting how simulation times were reduced

**Comment by cncastillo** [comment]
Everything here has already been done; congratulations again, Ryan!! Good luck with your last semester!!
