### ISSUE TITLE
Use color-map recommendations for MR relaxometry maps by Quantitative MR Study Group

### ISSUE THREAD

**Issue by cncastillo** [JuliaHealth/KomaMRI.jl#473]
### Feature Request

https://github.com/mfuderer/colorResources

I think it is important to adopt this standard. They have Julia scripts as well so it should be quite easy to add :smile:.

**Comment by aTrotier** [comment]
I am developing a package after talking to @mfuderer : https://github.com/aTrotier/qMRIColors.jl

When this package is ready, I will move it to @MagneticResonanceImaging and add it to the general repositories

**Comment by cncastillo** [comment]
Wow amazing!! I will definitely use it :)

**Comment by aTrotier** [comment]
The package is released : https://github.com/MagneticResonanceImaging/QMRIColors.jl

**Comment by cncastillo** [comment]
Thanks for writing this package! :smile: 

@Stockless this is a good second issue to target! (after #505).

**Comment by mfuderer** [comment]
Thank you - and congrats!
________________________________

**Comment by cncastillo** [comment]
Added in #528.
