### ISSUE TITLE
Troubles defining Float32 or empty phantoms with KomaMRI 0.9

### ISSUE THREAD

**Issue by Tooine** [JuliaHealth/KomaMRI.jl#498]
### What happened?

Hi, 

I switched to KomaMRI 0.9 and observed some performance improvements with simulations, which is great :+1: 

**Yet, I had some troubles (see below) with the way I define Float32 or empty phantoms with the new version.**
I am not sure if this is a bug or just the new expected behavior since 0.9, as for both situations, I found a (imo, less esthetic) way to define it as I want. 

Note that, **if this is not a bug, there might be parts of the documentation to modify**, like in the $T_2^*$ section of this [page](https://juliahealth.org/KomaMRI.jl/stable/tutorial-pluto/01-gradient-echo-spin-echo/), where the following empty phantom definition does not work anymore (at least for me)
```julia
# (3.1.1) Create an empty phantom
obj_t2star = Phantom{Float64}(x=[])
```

**Issue 1: Float32 vs Float64 phantom**
Creating a phantom encoded in Float32 like this leads to an error
```julia
Phantom{Float32}(x=[1.0])
→ ERROR: MethodError: Cannot `convert` an object of type NoMotion{Float64} to an object of type KomaMRIBase.AbstractMotion{Float32}
```
but this works fine and produces a phantom encoded in Float32 (including the motion!)
```julia
Phantom(x=Float32[1.0])
→ Phantom{Float32}
  name: String "spins"
  x: Array{Float32}((1,)) Float32[1.0]
  y: Array{Float32}((1,)) Float32[0.0]
  z: Array{Float32}((1,)) Float32[0.0]
  ρ: Array{Float32}((1,)) Float32[1.0]
  T1: Array{Float32}((1,)) Float32[1.0f6]
  T2: Array{Float32}((1,)) Float32[1.0f6]
  T2s: Array{Float32}((1,)) Float32[1.0f6]
  Δw: Array{Float32}((1,)) Float32[0.0]
  Dλ1: Array{Float32}((1,)) Float32[0.0]
  Dλ2: Array{Float32}((1,)) Float32[0.0]
  Dθ: Array{Float32}((1,)) Float32[0.0]
  motion: NoMotion{Float32} NoMotion{Float32}()
```

**Issue 2: Empty phantom**
Those commands do not work anymore
```julia
Phantom(x=[])
Phantom{Float32}(x=[])
Phantom{Float64}(x=[])
→ ERROR: MethodError: no method matching zero(::Type{Any})
```
But this works fine: 
```
Phantom(x=Float32[])
```

### Environment

```Markdown
OS x86_64-linux-gnu
Julia 1.10.2
KomaMRIPlots 0.9.0
KomaMRIFiles 0.9.0
KomaMRI 0.9.0
KomaMRICore 0.9.0
KomaMRIBase 0.9.0
```

**Comment by pvillacorta** [comment]
Thank you for posting this! This is indeed a bug, and is related to the new motion field in this new version. I will keep it in mind, as I now have an open PR (#495) where I can try to solve it.
Cheers
